// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import logger "github.com/gol4ng/logger"
import mock "github.com/stretchr/testify/mock"

// FormatterInterface is an autogenerated mock type for the FormatterInterface type
type FormatterInterface struct {
	mock.Mock
}

// Format provides a mock function with given fields: entry
func (_m *FormatterInterface) Format(entry logger.Entry) string {
	ret := _m.Called(entry)

	var r0 string
	if rf, ok := ret.Get(0).(func(logger.Entry) string); ok {
		r0 = rf(entry)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
