// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import logger "github.com/gol4ng/logger"
import mock "github.com/stretchr/testify/mock"

// LogInterface is an autogenerated mock type for the LogInterface type
type LogInterface struct {
	mock.Mock
}

// Log provides a mock function with given fields: message, level, context
func (_m *LogInterface) Log(message string, level logger.Level, context *logger.Context) error {
	ret := _m.Called(message, level, context)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, logger.Level, *logger.Context) error); ok {
		r0 = rf(message, level, context)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
