// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import logger "github.com/gol4ng/logger"
import mock "github.com/stretchr/testify/mock"

// LogInterface is an autogenerated mock type for the LogInterface type
type LogInterface struct {
	mock.Mock
}

// Log provides a mock function with given fields: message, level, field
func (_m *LogInterface) Log(message string, level logger.Level, field ...logger.Field) {
	_va := make([]interface{}, len(field))
	for _i := range field {
		_va[_i] = field[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, message, level)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}
